# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-101077-kali/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35ticsg324-1L

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/default
    /home/rehan/project_12/project_12.srcs/sources_1/imports/default
    /home/rehan/project_12/project_12.srcs/sources_1/ip/clk_wiz_0
  } {
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/include/el2_def.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/testbench/ahb_sif.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/apb_interconnect.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/apb_spi_master.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi2apb_64_32.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi_ar_buffer.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi_aw_buffer.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi_b_buffer.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi_interconnect.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/testbench/axi_lsu_dma_bridge.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi_r_buffer.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi_single_slice.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/axi_w_buffer.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/beh_lib.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dmi/dmi_jtag_to_core_sync.v
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dbg/el2_dbg.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dec/el2_dec.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dec/el2_dec_decode_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dec/el2_dec_gpr_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dec/el2_dec_ib_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dec/el2_dec_tlu_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dec/el2_dec_trigger.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/design/el2_dma_ctrl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/exu/el2_exu.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/exu/el2_exu_alu_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/exu/el2_exu_div_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/exu/el2_exu_mul_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu_aln_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu_bp_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu_compress_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu_ic_mem.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu_iccm_mem.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu_ifc_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/ifu/el2_ifu_mem_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/el2_lib.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_addrcheck.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_bus_buffer.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_bus_intf.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_clkdomain.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_dccm_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_dccm_mem.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_ecc.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_lsc_ctl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_stbuf.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lsu/el2_lsu_trigger.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/design/el2_mem.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/design/el2_pic_ctrl.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/design/el2_swerv.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/design/el2_swerv_wrapper.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/fifo_v3.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/lib/mem_lib.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/pwm.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dmi/rvjtag_tap.v
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/spi_master_apb_if.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/spi_master_clkgen.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/spi_master_controller.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/spi_master_fifo.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/spi_master_rx.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/spi_master_tx.sv
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/lib/timer.sv
      /home/rehan/project_12/project_12.srcs/sources_1/new/ReV-SoC_top_FPGA.sv
      /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
    }
      rt::read_verilog -include {
    /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/default
    /home/rehan/project_12/project_12.srcs/sources_1/imports/default
    /home/rehan/project_12/project_12.srcs/sources_1/ip/clk_wiz_0
  } {
      ./.Xil/Vivado-101077-kali/realtime/clk_wiz_0_stub.v
      /home/rehan/project_12/project_12.srcs/sources_1/imports/imports/dmi/dmi_wrapper.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-101077-kali/realtime/ReV_SoC_top_FPGA_synth.xdc
    rt::sdcChecksum
    set rt::top ReV_SoC_top_FPGA
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/rehan/project_12/project_12.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-101077-kali/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
